version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_auth
    environment:
      POSTGRES_USER: test         # This creates the 'test' user by default
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth           # This creates the 'auth' database
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork


  redis:
    image: redis:latest
    container_name: redis_container_geek
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge

